version: '3.1'
services:
  mongo:
    image: mongo:3.6
    ports: 
      - 27017:27017
  api:
    build:
      context: ./api
    entrypoint: ./entry.sh
    ports:
      - 9229:9229
      - 5000:5000
    volumes:
      - ./api:/var/www/api
    links:
      - mongo:mongo
    env_file:
      - ./secrets.env
    environment:
      - PORT=3000
      - VIRTUAL_HOST=api.trainer.com
      - VIRTUAL_PORT=3000
    depends_on:
      - mongo
  client:
    build:
      context: ./client
    ports:
      - "8080:8080"
    entrypoint: ./entry.sh
    volumes:
      - ./client:/var/www/client
    environment:
      - VIRTUAL_HOST=dev.trainer.com
    depends_on:
      - api
  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
