version: '3.1'
services:
  mongo:
    image: mongo:3.6
    ports: 
      - 27017:27017
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=trainer
      - POSTGRES_PASSWORD=tr@1n3r
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  api:
    build:
      context: ./api
    ports:
      - "9229:9229"
    entrypoint: ./entry.sh
    volumes:
      - ./api:/var/www/api
    links:
      - db:db
    env_file:
      - ./secrets.env
    environment:
      - PORT=3000
      - VIRTUAL_HOST=api.trainer.com
    depends_on:
      - db
  client:
    build:
      context: ./client
    ports:
      - "8080:8080"
    entrypoint: ./entry.sh
    volumes:
      - ./client:/var/www/client
    environment:
      - VIRTUAL_HOST=dev.trainer.com
    depends_on:
      - api
  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
