version: '3.1'
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=trainer
      - POSTGRES_PASSWORD=tr@1n3r
    ports:
      - 5432:5432
  rethinkdb:
    image: rethinkdb:latest
    ports:
      - 8081:8080
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
  api:
    build:
      context: ./api
    entrypoint: ./entry.sh
    volumes:
      - ./api:/var/www/api
    links:
      - postgres:db
      - rethinkdb:rethinkdb
    env_file:
      - ./secrets.env
    environment:
      - PORT=3000
      - VIRTUAL_HOST=api.trainer.com
    depends_on:
      - postgres
      - rethinkdb
  client:
    build:
      context: ./client
    ports:
      - "8080:8080"
    entrypoint: ./entry.sh
    volumes:
      - ./client:/var/www/client
    environment:
      - VIRTUAL_HOST=dev.trainer.com
    depends_on:
      - api
  proxy:
    build:
      context: ./proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
