version: '3.1'
services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    entrypoint: ./entry.sh
    volumes:
      - ./api:/var/www/api
    links:
      - db:db
    environment:
      - PORT=3000
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=trainer
      - POSTGRES_PASSWORD=tr@1n3r
